import {useEffect,useMemo,useState} from 'react';
import {Input} from 'baseui/input';
import {Textarea} from 'baseui/textarea';
import {Button} from 'baseui/button';
import type {ComponentType} from 'react';
import type {RoutineExercise,RoutineVersion,WorkoutSet} from '../types';
import {dateForDay} from '../lib/date';
import {EmojiIcon} from './EmojiIcon';

const BaseInput=Input as unknown as ComponentType<any>;
const BaseTextarea=Textarea as unknown as ComponentType<any>;
type DraftSet={reps:string;weight:string};
type DraftExercise={exercise:RoutineExercise;sets:DraftSet[];comment:string};

interface Props{version:RoutineVersion;week:number;monday:Date;exercises:RoutineExercise[];workouts:WorkoutSet[];onSubmit:(date:string,rows:WorkoutSet[])=>Promise<void>}
export function CurrentWeek({version,week,monday,exercises,workouts,onSubmit}:Props){
 const days=useMemo(()=>{const active=exercises.filter(e=>e.versionId===version.id&&week>=e.weekFrom&&week<=e.weekTo).sort((a,b)=>a.dayOrder-b.dayOrder||a.exerciseOrder-b.exerciseOrder); return [...new Set(active.map(e=>e.dayOrder))].map(order=>active.filter(e=>e.dayOrder===order))},[version,week,exercises]);
 const [page,setPage]=useState(0); useEffect(()=>setPage(p=>Math.min(p,Math.max(days.length-1,0))),[days.length]); const day=days[page];
 if(!day)return <><header><span className="eyebrow">Week {week} of {version.cycleWeeks}</span><h1>Current week</h1></header><p className="empty">No exercises this week.</p></>;
 const date=dateForDay(day[0].dayOfWeek,monday);
 return <><header className="compact-header"><span className="eyebrow">Week {week} of {version.cycleWeeks}</span><h1>Current week</h1><p>{day[0].dayName}<br/><time>{date} · 12:15–1:15 PM</time></p></header><DayEditor key={`${date}:${day.map(e=>e.exerciseId).join(':')}`} day={day} date={date} version={version} week={week} existing={workouts.filter(w=>w.sessionDate===date)} onSubmit={onSubmit}/>{days.length>1&&<Pager page={page} count={days.length} label="workout day" onPage={setPage} hideCount/>}</>;
}
function DayEditor({day,date,version,week,existing,onSubmit}:{day:RoutineExercise[];date:string;version:RoutineVersion;week:number;existing:WorkoutSet[];onSubmit:(date:string,rows:WorkoutSet[])=>Promise<void>}){
 const initial=()=>day.filter(exercise=>existing.length===0||existing.some(row=>row.exerciseId===exercise.exerciseId)).map(exercise=>{const saved=existing.filter(row=>row.exerciseId===exercise.exerciseId).sort((a,b)=>a.setNumber-b.setNumber); const count=saved.length||Math.max(exercise.sets,1); return {exercise,sets:Array.from({length:count},(_,i)=>({reps:saved[i]?.reps||'',weight:saved[i]?.weight||''})),comment:saved[0]?.comment||''}});
 const [draft,setDraft]=useState<DraftExercise[]>(initial); const [status,setStatus]=useState(''); const [expanded,setExpanded]=useState<string|null>(null); const [commenting,setCommenting]=useState<Set<string>>(()=>new Set(initial().filter(item=>item.comment).map(item=>item.exercise.exerciseId)));
 const changeSet=(exerciseId:string,index:number,field:keyof DraftSet,value:string)=>setDraft(items=>items.map(item=>item.exercise.exerciseId===exerciseId?{...item,sets:item.sets.map((set,i)=>i===index?{...set,[field]:value}:set)}:item));
 const addSet=(exerciseId:string)=>setDraft(items=>items.map(item=>item.exercise.exerciseId===exerciseId?{...item,sets:[...item.sets,{reps:'',weight:''}]}:item));
 const removeSet=(exerciseId:string)=>setDraft(items=>items.map(item=>item.exercise.exerciseId===exerciseId&&item.sets.length>1?{...item,sets:item.sets.slice(0,-1)}:item));
 const removeExercise=(exerciseId:string)=>{setDraft(items=>items.filter(item=>item.exercise.exerciseId!==exerciseId));setExpanded(current=>current===exerciseId?null:current);setCommenting(current=>{const next=new Set(current);next.delete(exerciseId);return next})};
 const toggleComment=(exerciseId:string)=>setCommenting(current=>{const next=new Set(current);next.has(exerciseId)?next.delete(exerciseId):next.add(exerciseId);return next});
 const submit=async()=>{setStatus('Submitting…'); const updatedAt=new Date().toISOString(); const rows=draft.flatMap(({exercise,sets,comment})=>sets.map((set,i)=>({recordId:`${date}:${exercise.exerciseId}:${i+1}`,sessionDate:date,versionId:version.id,cycleWeek:week,dayName:exercise.dayName,exerciseId:exercise.exerciseId,exerciseName:exercise.exerciseName,setNumber:i+1,reps:set.reps,weight:set.weight,comment:i===0?comment:'',updatedAt}))); try{await onSubmit(date,rows);setStatus('Submitted')}catch{setStatus('Submit failed — try again')}};
 return <div className="day-editor">{draft.map(item=>{const isExpanded=expanded===item.exercise.exerciseId;const isCommenting=commenting.has(item.exercise.exerciseId);const panelId=`exercise-${item.exercise.exerciseId}`;const commentId=`comment-${item.exercise.exerciseId}`;return <section className="current-exercise" key={item.exercise.exerciseId}><button className="exercise-row" type="button" aria-expanded={isExpanded} aria-controls={panelId} onClick={()=>setExpanded(current=>current===item.exercise.exerciseId?null:item.exercise.exerciseId)}><span><strong>{item.exercise.exerciseName}</strong><small>{item.exercise.targetReps} reps · {item.exercise.restSeconds}s rest</small></span><EmojiIcon name={isExpanded?'collapse':'expand'}/></button>{isExpanded&&<article className="exercise-details" id={panelId}><div className="exercise-actions"><Button kind="tertiary" onClick={()=>removeExercise(item.exercise.exerciseId)} aria-label={`Remove ${item.exercise.exerciseName}`}><EmojiIcon name="delete"/></Button></div><div className="set-head"><span>Set</span><span>Reps</span><span>lb</span></div>{item.sets.map((set,i)=><div className="set-row" key={i}><strong>{i+1}</strong><BaseInput aria-label={`${item.exercise.exerciseName} set ${i+1} reps`} inputMode="numeric" value={set.reps} onChange={(e:any)=>changeSet(item.exercise.exerciseId,i,'reps',e.currentTarget.value)}/><BaseInput aria-label={`${item.exercise.exerciseName} set ${i+1} weight`} inputMode="decimal" value={set.weight} onChange={(e:any)=>changeSet(item.exercise.exerciseId,i,'weight',e.currentTarget.value)}/></div>)}<div className="set-actions"><Button kind="secondary" onClick={()=>removeSet(item.exercise.exerciseId)} disabled={item.sets.length===1} aria-label={`Remove set from ${item.exercise.exerciseName}`}><EmojiIcon name="delete"/></Button><Button kind="secondary" onClick={()=>addSet(item.exercise.exerciseId)} aria-label={`Add set to ${item.exercise.exerciseName}`}><EmojiIcon name="add"/></Button><Button kind="secondary" onClick={()=>toggleComment(item.exercise.exerciseId)} aria-label={`${isCommenting?'Hide':'Add'} comment for ${item.exercise.exerciseName}`} aria-expanded={isCommenting} aria-controls={commentId}><EmojiIcon name="comment"/></Button></div>{isCommenting&&<div id={commentId}><BaseTextarea aria-label={`${item.exercise.exerciseName} comment`} placeholder="Optional comment" rows={1} value={item.comment} onChange={(e:any)=>setDraft(items=>items.map(value=>value.exercise.exerciseId===item.exercise.exerciseId?{...value,comment:e.currentTarget.value}:value))}/></div>}</article>}</section>})}{draft.length===0&&<p className="empty">All exercises removed from this workout.</p>}<div className="submit-row"><Button onClick={submit} isLoading={status==='Submitting…'}>Submit workout</Button><span aria-live="polite">{status}</span></div></div>;
}
export function Pager({page,count,label,onPage,hideCount=false}:{page:number;count:number;label:string;onPage:(page:number)=>void;hideCount?:boolean}){return <div className={`pagination${hideCount?' no-count':''}`}><Button disabled={page===0} onClick={()=>onPage(page-1)} aria-label={`Previous ${label}`}><EmojiIcon name="previous"/></Button>{!hideCount&&<strong>{page+1} / {count}</strong>}<Button disabled={page===count-1} onClick={()=>onPage(page+1)} aria-label={`Next ${label}`}><EmojiIcon name="next"/></Button></div>}
