import os from 'node:os';
import path from 'node:path';
import fs from 'node:fs';
import {google} from 'googleapis';
import {TopicGymTelegramBot} from './topic-gym-bot.mjs';
import {createStateStore} from './state-store.mjs';
import {createTelegramApi} from './telegram-api.mjs';
import {loadBootstrap,replaceSession,spreadsheetId} from '../server/workout-store.mjs';

const token=process.env.TELEGRAM_GYM_BOT_TOKEN;
const chatId=process.env.TELEGRAM_GYM_CHAT_ID;
if(!chatId)throw new Error('TELEGRAM_GYM_CHAT_ID is required');
const auth=new google.auth.GoogleAuth({scopes:['https://www.googleapis.com/auth/spreadsheets']});
const client=google.sheets({version:'v4',auth});
const sheetId=spreadsheetId();
const sheets={loadBootstrap:()=>loadBootstrap(client,sheetId),replaceSession:(date,rows)=>replaceSession(client,sheetId,date,rows)};
const statePath=process.env.TELEGRAM_GYM_STATE_PATH||path.join(os.homedir(),'.local','state','gym-routine-tracker','telegram.json');
const topicsPath=process.env.TELEGRAM_GYM_TOPICS_PATH||path.join(os.homedir(),'.local','state','gym-routine-tracker','topics.json');
const registered=JSON.parse(fs.readFileSync(topicsPath,'utf8')).topics||{};
const topics={current:1,history:7,context:12};
for(const id of Object.values(topics))if(!registered[id])throw new Error(`Telegram topic ${id} is not registered`);
const bot=new TopicGymTelegramBot({api:createTelegramApi(token),sheets,chatId,topics,stateStore:createStateStore(statePath),contextPath:path.resolve('WORKOUT_CONTEXT.md')});
await bot.start();
