import {describe,expect,it,vi} from 'vitest';
import {TopicGymTelegramBot,markdownToTelegram} from './topic-gym-bot.mjs';

const data={versions:[{id:'v1',name:'Routine',effectiveFrom:'2026-01-01',effectiveTo:'',cycleWeeks:1,notes:''}],exercises:[{versionId:'v1',weekFrom:1,weekTo:1,dayOfWeek:1,dayName:'Monday',dayOrder:1,exerciseId:'squat',exerciseName:'Squat',exerciseOrder:1,sets:1,targetReps:'5',restSeconds:180,equipment:'Barbell',instructions:'',supersetId:'',guidance:''}],workouts:[{recordId:'r1',sessionDate:'2026-09-07',versionId:'v1',cycleWeek:1,dayName:'Monday',exerciseId:'squat',exerciseName:'Squat',setNumber:1,reps:'5',weight:'100',comment:'Solid',updatedAt:'2026-09-07T20:00:00Z'}],stats:[{exerciseId:'squat',exerciseName:'Squat',period:'all',sessions:'1',firstWeight:'100',latestWeight:'100',bestWeight:'100',change:'0',changePercent:'0%',lastPerformed:'2026-09-07'}]};
function setup(){const calls=[];let id=20;const api={call:vi.fn(async(method,body)=>{calls.push([method,body]);if(method==='sendMessage'||method==='sendRichMessage')return {message_id:id++};return true})};const sheets={loadBootstrap:vi.fn(async()=>structuredClone(data)),replaceSession:vi.fn(async()=>{})};const state={};const stateStore={load:()=>state,save:vi.fn(value=>Object.assign(state,structuredClone(value)))};const bot=new TopicGymTelegramBot({api,sheets,chatId:'42',topics:{current:1,history:7,context:12},stateStore,contextPath:'WORKOUT_CONTEXT.md',now:()=>new Date('2026-09-07T12:00:00')});return {bot,api,sheets,calls,state}}

describe('TopicGymTelegramBot',()=>{
 it('converts workout Markdown into Telegram formatting blocks',()=>{const formatted=markdownToTelegram('# Workout context\n\n## Personal context\n\n- Goal: grow\n\nSee [program](https://example.com).');expect(formatted).toContain('🏋️ <b>Workout context</b>');expect(formatted).toContain('👤 <b>Personal context</b>');expect(formatted).toContain('• Goal: grow');expect(formatted).toContain('<a href="https://example.com">program</a>')});
 it('sends the current dashboard only to the Current topic',async()=>{const {bot,calls}=setup();await bot.refresh();await bot.renderCurrent();const body=calls.at(-1)[1];expect(body.message_thread_id).toBe(1);expect(body.reply_markup.inline_keyboard.flat().map(item=>item.text)).toContain('Stats')});
 it('renders Stats only after an inline interaction in Current',async()=>{const {bot,calls}=setup();await bot.refresh();await bot.renderCurrent();calls.length=0;await bot.handle({callback_query:{id:'q',message:{chat:{id:42},message_thread_id:1},data:'stats'}});expect(calls.some(([method,body])=>method==='editMessageText'&&body.message_thread_id===1&&body.text.includes('<b>Stats</b>'))).toBe(true);expect(calls.some(([method,body])=>method==='sendMessage'&&body.message_thread_id!==1)).toBe(false)});
 it('posts context once and edits it when a preference overrides it',async()=>{const {bot,state,calls}=setup();await bot.renderContext();expect(calls.at(-1)[1]).toMatchObject({message_thread_id:12,parse_mode:'HTML',link_preview_options:{is_disabled:true}});expect(calls.at(-1)[1].text).toContain('🏋️ <b>Workout context</b>');calls.length=0;await bot.handle({message:{chat:{id:42},message_thread_id:12,text:'/context Prefer lower volume.',message_id:31,date:1788800000}});expect(state.contextPreference.text).toBe('Prefer lower volume.');expect(state.contextHistory).toHaveLength(1);expect(calls.some(([method,body])=>method==='editMessageText'&&body.text.includes('<blockquote><b>Latest preference override</b>'))).toBe(true)});
 it('publishes one emoji-free rich History post per workout date',async()=>{const {bot,calls,state}=setup();await bot.refresh();await bot.syncHistory();const posts=calls.filter(([method])=>method==='sendRichMessage');expect(posts).toHaveLength(1);expect(posts[0][1]).toMatchObject({message_thread_id:7,rich_message:{skip_entity_detection:true}});const markdown=posts[0][1].rich_message.markdown;expect(markdown).toContain('# 2026\\-09\\-07');expect(markdown).toContain('<details><summary>Squat</summary>');expect(markdown).toContain('| 1 | 100 lb | 5 |');expect(markdown).toContain('> Solid');expect(markdown).toContain('</details>');expect(markdown).not.toMatch(/\p{Extended_Pictographic}/u);expect(Object.keys(state.historyMessages)).toEqual(['2026-09-07'])});
 it('separates exercise groups but keeps exercises inside a superset together',()=>{const {bot}=setup();bot.data={exercises:[{versionId:'v1',exerciseId:'a',supersetId:''},{versionId:'v1',exerciseId:'b',supersetId:'pair'},{versionId:'v1',exerciseId:'c',supersetId:'pair'},{versionId:'v1',exerciseId:'d',supersetId:''}]};const exercise=(id,name)=>({id,name,sets:[{versionId:'v1',setNumber:1,weight:'10',reps:'5'}]});const markdown=bot.historyRichMessage({date:'2026-09-07',dayName:'Monday',exercises:[exercise('a','A'),exercise('b','B'),exercise('c','C'),exercise('d','D')]}).markdown;expect(markdown.match(/^---$/gm)).toHaveLength(3);expect(markdown).toContain('</details>\n\n---\n## Superset\n<details><summary>B</summary>');expect(markdown).toContain('</details>\n\n<details><summary>C</summary>');expect(markdown).toContain('</details>\n\n---\n<details><summary>D</summary>')});
 it('updates an existing History post using rich content',async()=>{const {bot,calls}=setup();bot.state.historyMessages={'2026-09-07':41};await bot.refresh();await bot.syncHistory();expect(calls.at(-1)).toEqual(['editMessageText',expect.objectContaining({message_id:41,rich_message:expect.objectContaining({markdown:expect.stringContaining('| Set | Weight | Reps |')})})])});
 it('rejects callbacks outside Current',async()=>{const {bot,api}=setup();await bot.handle({callback_query:{id:'q',message:{chat:{id:42},message_thread_id:7},data:'stats'}});expect(api.call).toHaveBeenCalledWith('answerCallbackQuery',expect.objectContaining({show_alert:true}))});
});
